[package]
name = "uuid_v1_variant"
version = "0.1.0"
authors = ["Edward Tate <cmalune@gmail.com>"]
repository = "https://github.com/et4te/uuid"
license = "MIT"
exclude = [ ".gitignore" ]

[dependencies]
rustc-serialize = "0.3"
rand = "0.3"
